/*
 * TetrisView.java
 */

package tetris;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Label;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Date;
import org.jdesktop.application.SingleFrameApplication;
import org.jdesktop.application.FrameView;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.Timer;
import javax.swing.border.Border;
import javax.swing.border.LineBorder;

/**
 * The application's main frame.
 */
public class TetrisView extends FrameView {

    public TetrisView(SingleFrameApplication app) {
        super(app);
        
        initComponents();

        //Ocultar el mensaje "Has perdido"
        perdido.setVisible(false);

        //Ventana no puede cambiar de tamaño
        this.getFrame().setResizable(false);

        //Tamaño predefinido para la ventana
        //Ancho: 12 * ancho de un cuadro de pieza (20px)
        //Alto: 25 * alto de un cuadro de pieza (20px)
        this.getFrame().setPreferredSize(new Dimension(12 * 20, 25 * 20));
        this.getFrame().setSize(new Dimension(12 * 20, 25 * 20));

        //Esto hace que podamos poner las cosas donde
        //queramos.
        mainPanel.setLayout(null);
    }

    public Pieza dibujar_pieza(Pieza p) {
        p.removeAll();

        for(int i=0;i<p.la_pieza.length;i++) {
            for(int k=0;k<p.la_pieza[i].length;k++) {
                if(p.la_pieza[i][k] == true) {
                    Label c = new Label();
                    c.setPreferredSize(new Dimension(19,19));
                    c.setSize(new Dimension(19,19));
                    c.setLocation(20*k, 20*i);
                    c.setText("");
                    c.setBackground(p.color_de_la_pieza);
                    p.add(c);
                }
            }
        }
        
        p.setPreferredSize(new Dimension(p.la_pieza[0].length * 20, p.la_pieza.length * 20));
        p.setSize(new Dimension(p.la_pieza[0].length * 20, p.la_pieza.length * 20));
        p.setLocation(p.posX, p.posY);
        mainPanel.add(p);

        return p;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        perdido = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(tetris.TetrisApp.class).getContext().getResourceMap(TetrisView.class);
        mainPanel.setBackground(resourceMap.getColor("mainPanel.background")); // NOI18N
        mainPanel.setAlignmentX(0.0F);
        mainPanel.setAlignmentY(0.0F);
        mainPanel.setName("mainPanel"); // NOI18N

        perdido.setBackground(resourceMap.getColor("perdiste.background")); // NOI18N
        perdido.setName("perdiste"); // NOI18N
        perdido.setPreferredSize(new java.awt.Dimension(240, 142));
        perdido.setSize(new java.awt.Dimension(240, 142));

        jLabel1.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        jLabel1.setForeground(resourceMap.getColor("jLabel1.foreground")); // NOI18N
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        jLabel2.setForeground(resourceMap.getColor("jLabel1.foreground")); // NOI18N
        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel2.setName("jLabel2"); // NOI18N

        org.jdesktop.layout.GroupLayout perdidoLayout = new org.jdesktop.layout.GroupLayout(perdido);
        perdido.setLayout(perdidoLayout);
        perdidoLayout.setHorizontalGroup(
            perdidoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(perdidoLayout.createSequentialGroup()
                .add(12, 12, 12)
                .add(perdidoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.CENTER)
                    .add(jLabel1)
                    .add(jLabel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .add(53, 53, 53))
        );
        perdidoLayout.setVerticalGroup(
            perdidoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(perdidoLayout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 40, Short.MAX_VALUE)
                .add(jLabel2)
                .addContainerGap())
        );

        org.jdesktop.layout.GroupLayout mainPanelLayout = new org.jdesktop.layout.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 759, Short.MAX_VALUE)
            .add(mainPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(mainPanelLayout.createSequentialGroup()
                    .add(0, 256, Short.MAX_VALUE)
                    .add(perdido, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 247, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(0, 256, Short.MAX_VALUE)))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 308, Short.MAX_VALUE)
            .add(mainPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(mainPanelLayout.createSequentialGroup()
                    .add(0, 83, Short.MAX_VALUE)
                    .add(perdido, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(0, 83, Short.MAX_VALUE)))
        );

        setComponent(mainPanel);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JPanel mainPanel;
    public javax.swing.JPanel perdido;
    // End of variables declaration//GEN-END:variables

}
